
# Define a versão do Docker Compose que está sendo usada
version: "3.8"

# "services" define os containers que fazem parte da aplicação (backend, frontend e db)
services:

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    networks:
      - sd_kawi
    depends_on:
      - backend

  backend:
    image: node:20 
    working_dir: /src/
    depends_on:
      - postgresql-master
    volumes: 
      - ./backend:/src/
    ports: 
      - "3333"
    command: bash -c "npm run dev && npx prisma migrate dev"
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://my_user:my_password@postgresql-master:5432/my_database
    networks:
      - sd_kawi

  frontend:
    image: node:20
    container_name: frontend-container
    working_dir: /home/node/app
    volumes:
      - ./frontend:/home/node/app
    ports:
      - "5173:5173"
    depends_on:
      - backend
    command: npm run dev --host 0.0.0.0
    networks:
      - sd_kawi

  postgresql-master:
    image: 'bitnami/postgresql:latest'
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_master_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_USERNAME=my_user
      - POSTGRESQL_PASSWORD=my_password
      - POSTGRESQL_DATABASE=my_database
    networks:
      - sd_kawi

  postgresql-slave:
    image: 'bitnami/postgresql:latest'
    ports:
      - '5433:5432'
    depends_on:
      - postgresql-master
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_MASTER_HOST=postgresql-master
      - POSTGRESQL_PASSWORD=my_password
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
    networks:
      - sd_kawi
      
volumes:
  postgresql_master_data:
  
networks:
  sd_kawi:
    driver: bridge